version: "3.8"

services:
  downloadsong-service:
    image: andreasoliz17/downloadsong:1.0
    container_name: downloadsong-service
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production
    command: ["node", "index.js"]

  listsong-service:
    image: d3nnys/song-service:latest
    container_name: listsong-service
    ports:
      - "9000:8000"
    volumes:
      - .:/listsongservice
    environment:
      - APP_ENV=production
    command: ["php", "artisan", "serve", "--host=0.0.0.0", "--port=8000"]

  auth_service:
    image: eamll/auth-service-python:latest
    container_name: auth-service-python
    ports:
      - "9001:9001"
    environment:
      - SECRET_KEY=your-secret-key-here
    volumes:
      - ./app:/python-app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9001/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
